{{ if.Values.admin.vault.vaultPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-admin
spec:
    secretStoreRef:
      name: {{ .Values.admin.vault.secretStore }}
      kind: SecretStore  # or ClusterSecretStore
    refreshInterval: "1h"
    target:
      name: pgadmin-admin
      creationPolicy: Owner
      deletionPolicy: Delete
    data:
      - secretKey: email
        remoteRef:
          key: {{ .Values.admin.vault.vaultPath }}
          property: email
      - secretKey: password
        remoteRef:
          key: {{ .Values.admin.vault.vaultPath }}
          property: password
{{ end }}
