{{ if .Values.storage.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-claim
  namespace: {{ .Release.Namespace  }}
  labels:
    app: pgadmin
spec:
  storageClassName: {{ .Values.storage.class }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{ end }}
