{{ if .Values.admin.value.password }}
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-admin
type: Opaque
data:
  email: {{ .Values.admin.value.email | b64enc }}
  password: {{ .Values.admin.value.password | b64enc }}
{{ end }}