{{- if and .Values.s3Secret.accessKey .Values.s3Secret.secretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kdp-metastore.s3SecretName" . }}
  labels:
    {{- include "kdp-metastore.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  accessKey: {{ .Values.s3Secret.accessKey | b64enc | quote }}
  secretKey: {{ .Values.s3Secret.secretKey | b64enc | quote }}
{{- end }}

