{{ if .Values.firstStaticClient.id }}
{{ with .Values.firstStaticClient }}
---
apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: {{ .secretName | default (printf "%s-client-secret" .id) }}
spec:
  data:
    clientId: {{ .id }}     # Some client will look in the secret for the clientId also. (i.e argo workflow)
  fields:
    - fieldName: "clientSecret"
      encoding: "base64"
      length: "15"
{{ end }}
{{ end }}

{{ range .Values.staticClients }}
---
apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: {{ .secretName | default (printf "%s-client-secret" .id) }}
spec:
  data:
    clientId: {{ .id }}     # Some client will look in the secret for the clientId also. (i.e argo workflow)
  fields:
    - fieldName: "clientSecret"
      encoding: "base64"
      length: "15"
data:
{{ end }}

