{{ if .Values.oidc.ca.crt }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dexgate.name" . }}-oidc-ca
  namespace: {{ .Release.Namespace  }}
data:
  ca.crt: {{ .Values.oidc.ca.crt }}

{{ end }}
