apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dexgate.name" . }}-config
  namespace: {{ .Release.Namespace  }}
data:
  config.yaml: |
    ---
    logMode: {{ .Values.logMode }}
    logLevel:   "{{ .Values.logLevel }}"
    targetURL: "{{ .Values.proxy.targetURL }}"
    passthroughs: [ "/favicon.ico" ]
    tokenDisplay: {{ .Values.tokenDisplay }}
    usersConfigMap:
      configMapName: {{ include "dexgate.name" . }}-users
    oidc:
      {{- if .Values.oidc.clientID.secret.name }}
      clientIDEnv: CLIENT_ID
      {{- else }}
      clientID: {{ required "Missing clientID" .Values.oidc.clientID.value }}
      {{- end }}
      {{- if .Values.oidc.clientSecret.secret.name }}
      clientSecretEnv: CLIENT_SECRET
      {{- else }}
      clientSecret: {{ required "Missing clientSecret" .Values.oidc.clientSecret.value }}
      {{- end }}
      issuerURL: {{ .Values.oidc.issuerURL }}
      redirectURL: https://{{ .Values.ingress.host }}/dg_callback
      {{- with .Values.oidc.loginURLOverride }}
      loginURLOverride: {{ . }}
      {{- end }}
      scopes:
        - profile
        - groups
        - email
      debug: {{ .Values.oidc.debug }}
