{{ if .Values.oidc.encodedClientID }}
---
apiVersion: dex.coreos.com/v1
kind: OAuth2Client
metadata:
  name: {{ .Values.oidc.encodedClientID }}
  namespace: {{ .Values.oidc.dexNamespace }}
name: {{ required "oidc.clientID.value is required if oidc.encodedClientID is defined" .Values.oidc.clientID.value }}
id: {{ .Values.oidc.clientID.value }}
secret: {{  required "oidc.clientSecret.value is required if oidc.encodedClientID is defined" .Values.oidc.clientSecret.value }}
public: false
redirectURIs:
  - https://{{ .Values.ingress.host }}/dg_callback

{{ end }}

