---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ include "dexgate.name" . }}
  name: {{ include "dexgate.name" . }}
  namespace: {{ .Release.Namespace  }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dexgate.name" . }}
  namespace: {{ .Release.Namespace  }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dexgate.name" . }}
  namespace: {{ .Release.Namespace  }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dexgate.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dexgate.name" . }}
    namespace: {{ .Release.Namespace  }}  # The namespace dex is running in
