apiVersion: v1
kind: Namespace
metadata:
  name: {{ required "The namespace must be defined in value file" .Values.namespace }}
  labels:
      {{- include "workspace.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
